name = "google-drive-personal-mcp"
main = "src/index.js"
compatibility_date = "2026-09-20"

[[kv_namespaces]]
binding = "GOOGLE_TOKENS"
id = "322d31395dd84fbdbae1b3e2f6939574"

[vars]
GOOGLE_API_BASE = "https://www.googleapis.com"
GOOGLE_REDIRECT_URI = "https://google-drive-personal-mcp.adam-efc.workers.dev/callback"
